#version 460

layout(local_size_x = 16) in;

layout(push_constant) uniform Params
{
    uint n;
} params;
layout(set = 0, binding = 1) readonly buffer inputA
{
    float A[];
};
layout(set = 0, binding = 2) readonly buffer inputB
{
    float B[];
};
layout(set = 0, binding = 3) buffer output
{
    float C[];
};
void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.n)
        return;
    C[i] = A[i] + B[i];
}