#version 460

layout(local_size_x = 16) in;

layout(push_constant) uniform PushConstants {
    uint B;
    uint M;
    uint N;
    uint K;
    float eps;
} params;

layout(std430, set = 0, binding = 0) readonly buffer bufferA { float A[]; };
layout(std430, set = 0, binding = 1) readonly buffer bufferB { float B[]; };
layout(std430, set = 0, binding = 2) writeonly buffer bufferC { float C[]; };

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.M)
        return;
    C[i] = A[i] + B[i];
}