#version 460

layout(local_size_x = 256) in;

layout(push_constant) uniform PushConstants {
    uint batch;
    uint M;
    uint N;
    uint K;
    float eps;
} params;

layout(std430, set = 0, binding = 0) buffer bufferA { float A[]; };

const float SQRT_2_OVER_PI = 0.7978845608028654;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.N) return;
    
    float x = A[i];
    float xcube = x * x * x;
    
    float inner = SQRT_2_OVER_PI * (x + 0.044715 * xcube);
    A[i] = 0.5 * x * (1.0 + tanh(inner));
}