#version 460

// flags = masking_flag
layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform PushConstants {
    uint batch;
    uint M;
    uint N;
    uint K;
    float eps;
    uint flags;
} params;

layout(std430, set = 0, binding = 0) writeonly buffer bufferA { float A[]; };

void main() {
    uint col = gl_GlobalInvocationID.x;
    uint row = gl_GlobalInvocationID.y;
    
    if (row >= params.M || col >= params.N || col <= row) {
        return;
    }
    float neginf = -1.0f / 0.0f;
    A[row * params.N + col] = neginf * float(params.flags);
}