#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform PushConstants {
    uint B;
    uint M;
    uint N;
    uint K;
    float eps;
} params;

layout(set = 0, binding = 0) readonly buffer bufferA { float A[]; };
layout(set = 0, binding = 1) readonly buffer bufferB { float B[]; };
layout(set = 0, binding = 2) buffer bufferC { float C[]; };

void main() {
    uint col = gl_GlobalInvocationID.x;
    uint row = gl_GlobalInvocationID.y;
    
    if (row >= params.M || col >= params.N) {
        return;
    }
        
    float sum = 0.0f;
    
    for(uint i = 0; i < params.K; i++) {
        sum = fma(A[row * params.K + i], B[i * params.N + col], sum);
    }
    
    C[row * params.N + col] = sum;
}