#version 460
#extension GL_EXT_shader_atomic_float : require
// use this shader in softmax.c in replace of first loop of finding normalizer, 
// normalizer should 0.0f before calling this
layout(local_size_x = 16) in;
layout(push_constant) uniform PushConstants {
    uint batch;
    uint M;
    uint N;
    uint K;
    float eps;
    uint flags;
} params;

layout(std430, set = 0, binding = 0) readonly buffer bufferA { float A[]; };
layout(std430, set = 0, binding = 1) writeonly buffer bufferC { float C[]; };
layout(std430, set = 0, binding = 2) buffer Data {
    float normalizer;
} data;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.N)
        return;
    float x = exp(A[i]);
    C[i] = x;
    atomicAdd(data.normalizer, x);
}