#version 460
#extension GL_EXT_shader_atomic_float : require

layout(local_size_x = 16) in;
// RMS_square should be 0 before call
layout(push_constant) uniform PushConstants {
    uint batch;
    uint M;
    uint N;
    uint K;
    float eps;
    uint flags;
} params;

layout(std430, set = 0, binding = 0) readonly buffer bufferA { float A[]; };
layout(std430, set = 0, binding = 1) buffer Data {
    float RMS_square;
} data;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.N)
        return;
    float x = (A[i] * A[i]) / float(params.N);
    atomicAdd(data.RMS_square, x);
}